### ISSUE TITLE
Download QRCode

### ISSUE THREAD

**Issue by leouie28** [guilhermeasn/react-qrcode-pretty#1]
Just wondering if there is available built-in download function

**Comment by leouie28** [comment]
Not very important issue

**Comment by guilhermeasn** [comment]
This package does not have this feature, but you can implement it with packages designed for this, such as downloadjs https://www.npmjs.com/package/downloadjs

**Comment by guilhermeasn** [comment]
example https://github.com/guilhermeasn/react-qrcode-pretty/blob/example/src/App.tsx

**Comment by guilhermeasn** [comment]
now with v3 it is possible to download qrcode with react hook useQrcodeDownload
